#+TITLE:    The clim.flamegraph system
#+AUTHOR:   Jan Moringen
#+EMAIL:    jmoringe@techfak.uni-bielefeld.de
#+LANGUAGE: en

#+OPTIONS: num:nil toc:nil
#+SEQ_TODO: TODO STARTED | DONE

* Introduction

  The ~clim.flamegraph~ system is a proof of concept application for
  [[https://common-lisp.net/project/mcclim/][McCLIM]] that displays profiling data recorded uses [[http://sbcl.org][SBCL]]'s ~sb-sprof~
  contrib module as a flamegraph, i.e. a visualization of the relative
  frequencies of function call chains.

  *This system uses an interface that has been introduced in SBCL
  1.4.6, so at least that SBCL version is required*.

  *SBCL 1.4.13 includes an important performance improvement for
  sorting profiling results. If redisplay performance is not good
  enough, try using that SBCL version.*

* TODO Tutorial

* STARTED Glossary

  + <<glossary:run>> run :: A run is a collection of coherent [[glossary:trace][traces]],
       usually collected in a single profiling session.

       A run can contain [[glossary:trace][traces]] for multiple threads.

  + <<glossary:trace>> trace :: A trace is a snapshot of a thread's
       execution state (i.e. stack trace) at a given time. It is an
       ordered sequence of [[glossary:sample][samples]] describing the stack of active
       function invocations.

  + <<glossary:sample>> sample :: A sample is a representation of an
       active function invocation in a given thread at a given time.

  + <<glossary:node>> node ::

  + <<glossary:region>> region ::
